import type {Metadata} from 'next';
import './globals.css';
import localFont from 'next/font/local'

// Font files can be colocated inside of `app`
const breamcatcher = localFont({ src: './BreamCatcher.otf' })


export const metadata: Metadata = {
  title: 'Firebase Studio App',
  description: 'Generated by Firebase Studio',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${breamcatcher.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}


